return {
	["Factory"] = { Boss = "Core", world = "w2" },
	["Auto Pole 1"] = { Boss = "Thunder God", hop = "HOP Pole 1", world = "w1" },
	["Auto Trident"] = { Boss = "Fishman Lord", hop = "HOP Trident", world = "w1" },
	["Auto Bazooka"] = { Boss = "Wysper", hop = "HOP Bazooka", world = "w1" },
	["Auto CoolShade"] = { Boss = "Cyborg", hop = "HOP CoolShade", world = "w1" },
	["Auto LongSword"] = { Boss = "Diamond", hop = "HOP LongSword", world = "w2" },
	["Auto GravityBlade"] = { Boss = "Fajita", hop = "HOP GravityBlade", world = "w2" },
	["Auto SwanGlasses"] = { Boss = "Don Swan", hop = "HOP SwanGlasses", world = "w2" },
	["Auto Flail"] = { Boss = "Smoke Admiral", hop = "HOP Flail", world = "w2" },
	["Auto DragonTrident"] = { Boss = "Tide Keeper", hop = "HOP DragonTrident", world = "w2" },
	["Auto PilotHelmet"] = { Boss = "Stone", hop = "HOP PilotHelmet", world = "w3" },
	["Auto VenomBow"] = { Boss = "Hydra Leader", hop = "HOP VenomBow", world = "w3" },
	["Auto Lei"] = { Boss = "Kilo Admiral", hop = "HOP Lei", world = "w3" },
	["Auto TwinHooks"] = { Boss = "Captain Elephant", hop = "HOP TwinHooks", world = "w3" },
	["Auto Canvender"] = { Boss = "Beautiful Pirate", hop = "HOP Canvender", world = "w3" },
	["Auto BuddySword"] = { Boss = "Cake Queen", hop = "HOP BuddySword", world = "w3" },
	["Auto Darkbeard"] = { Boss = "Darkbeard", hop = "HOP Darkbeard", world = "w2" },
	["Auto HallowScythe"] = { Boss = "Soul Reaper", hop = "HOP HallowScythe", world = "w3" },
	["Indra"] = { Boss = "Rip indra", hop = "HOP Indra", world = "w3" },
}
